import { makeStyles } from "@mui/styles";

const useStyles = makeStyles(() => ({
  
  contentGrowthI: {
    display: 'flex',
    width: '540px',
    background: 'white',
    flexDirection: 'column',
    justifyContent: 'center',
    padding: '20px',
    borderRadius: '16px',
    gap: '16px',
    alignSelf: 'stretch'
  }, 
  contentWhole: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'flex-start',
    gap: '16px',
    flex: '1 0 0',
    alignSelf: 'stretch'
  },
  contentQ1: {
    display: 'flex',
    height: '261.612px',
    alignItems: 'flex-start',
    gap: '16px',
    alignSelf: 'stretch'
  },
  // contentRevenue: {
  //   display: 'flex',
  //   minWidth: '32%',
  //   padding: '24px',
  //   flexDirection: 'column',
  //   alignItems: 'flex-start',
  //   gap: '8px',
  //   flex: '1 0 0',
  //   alignSelf: 'stretch',
  //   borderRadius: '16px',
  //   background: 'var(--White, #FFF)',
  // },
  contentLostdeals: {
    display: 'flex',
    minWidth: '320px',
    minHeight: '200px',
    padding: '24px',
    flexDirection: 'column',
    alignItems: 'flex-start',
    gap: '8px',
    flex: '1 0 0',
    alignSelf: 'stretch',
    borderRadius: '16px',
    background: 'var(--White, #FFF)',
  },
  title: {
    display: 'flex',
    paddingBottom: '16px',
    alignItems: 'flex-start',
    gap: '8px',
    alignSelf: 'stretch',
  },
  subtitle: {
    color: '#131313',
    fontFamily: 'Inter',
    fontSize: '48px',
    fontStyle: 'normal',
    fontWeight: '500',
    lineHeight: 'normal',
    letterSpacing: '-2px',
  },
  subtitle1: {
    color: '#454545',
    fontFamily: 'Inter',
    fontSize: '14px',
    fontStyle: 'normal',
    fontWeight: '400',
    lineHeight: 'normal',
    letterSpacing: '-0.3px',
  },
  contentQuarterdeals: {
    display: 'flex',
    minWidth: '260px',
    minHeight: '200px',
    padding: '24px',
    flexDirection: 'column',
    alignItems: 'center',
    gap: '8px',
    alignSelf: 'stretch',
    borderRadius: '16px',
    background: 'var(--White, #FFF)',
  },
  contentQ2: {
    display: 'flex',
    alignItems: 'flex-start',
    gap: '16px',
    height: '50%',
    alignSelf: 'stretch',
  },
  contentCustomers: {
    display: 'flex',
    minHeight: 'auto',
    // height: '400px', // Adjusted to use string value
    minWidth: '40%',
    padding: '24px 0', // Adjusted padding shorthand
    flexDirection: 'column',
    alignItems: 'flex-start',
    flex: '1 0 0',
    borderRadius: '16px',
    background: 'var(--White, #FFF)',
    height: 'auto'
  },
  contentGrowth: {
    // display: 'flex',
    // width: '540px',
    // flexDirection: 'column',
    // alignItems: 'flex-start',
    // gap: '16px',
    // alignSelf: 'stretch'
    display: 'flex',
    width: '540px',
    background: 'white',
    flexDirection: 'column',
    justifyContent: 'center',
    padding: '20px',
    borderRadius: '16px',
    gap: '16px',
    alignSelf: 'stretch'
  },
  contentQ3: {
    display: 'flex',
    alignItems: 'flex-start',
    gap: '16px',
    alignSelf: 'stretch'
  },
  contentChat: {
    display: 'flex',
    minWidth: '27%',
    padding: '24px',
    flexDirection: 'column',
    alignItems: 'flex-start',
    gap: '8px',
    alignSelf: 'stretch',
    borderRadius: '16px',
    background: 'var(--White, #FFF)',

  },
  contentTopstates: {
    display: 'flex',
    minWidth: '320px',
    padding: '24px',
    flexDirection: 'column',
    alignItems: 'flex-start',
    gap: '8px',
    alignSelf: 'stretch',
    borderRadius: '16px',
    background: 'var(--White, #FFF)',
  },
  contentNewdeals: {
    display: 'flex',
    minWidth: 'auto',
    padding: '24px',
    flexDirection: 'column',
    alignItems: 'flex-start',
    gap: '8px',
    alignSelf: 'stretch',
    borderRadius: '16px',
    background: 'var(--White, #FFF)',
    flex: '1 0 0'
  },
  customerTitleBox: {
    display: 'flex',
    flexDirection: 'row',
    padding: '0px 24px',
    justifyContent: 'space-between',
    alignItems: 'center',
    alignSelf: 'stretch',
    marginBottom: '30px',
  },
  customerTitle: {
    color: '#131313',
    fontFamily: 'Inter !important',
    fontSize: '20px !important',
    fontStyle: 'normal !important',
    fontWeight: '600 !important',
    lineHeight: 'normal !important',
    letterSpacing: '-0.2px !important',
  },
  titleRight: {
    color: '#454545',
    fontFamily: 'Inter',
    fontSize: '14px',
    fontStyle: 'normal',
    fontWeight: '400',
    lineHeight: 'normal',
    letterSpacing: '-0.3px',
  },
  linktext: {
    display: 'flex',
    color: '#734A00',
    alignSelf: 'stretch',
    alignItems: 'center',
    padding: '24px',
    fontFamily: 'Inter',
    fontSize: '14px',
    fontStyle: 'normal',
    fontWeight: '400',
    lineHeight: 'normal',
    letterSpacing: '-0.3px',
    marginLeft: '12px',
  },
  linkBox: {
    display: 'flex',
    flexDirection: 'row',
    gap: '6px',
    alignItems: "center",
  },
  profileWindow: {
    display: "flex",
    alignItems: "center",
    alignContent: "center",
    gap: "8px",
    alignSelf: "stretch",
    flexWrap: "wrap",
    marginTop: '15px'
  },
  profileAvatar: {
    display: "flex",
    padding: '12px',
    alignItems: "center",
    gap: "8px",
  },
  customerCity: {
    display: "flex",
    padding: '6px 8px',
    gap: '8px',
    justifyContent: 'space-between',
    width: '100%',
    borderRadius: '4px',
    marginTop: '18px',
    background: 'linear-gradient(90deg, #FFCD71 -2.57%, rgba(255, 205, 113, 0.00) 112.5%)'
  },
  customerCity2: {
    display: "flex",
    padding: '6px 8px',
    gap: '8px',
    justifyContent: 'space-between',
    width: '80%',
    borderRadius: '4px',
    background: 'linear-gradient(90deg, #FFCD71 -2.57%, rgba(255, 205, 113, 0.00) 112.5%)'
  },
  customerCity3: {
    display: "flex",
    padding: '6px 8px',
    gap: '8px',
    justifyContent: 'space-between',
    width: '70%',
    borderRadius: '4px',
    background: 'linear-gradient(90deg, #FFCD71 -2.57%, rgba(255, 205, 113, 0.00) 112.5%)'
  },
  customerCity4: {
    display: "flex",
    padding: '6px 8px',
    gap: '8px',
    justifyContent: 'space-between',
    width: '50%',
    borderRadius: '4px',
    background: 'linear-gradient(90deg, #FFCD71 -2.57%, rgba(255, 205, 113, 0.00) 112.5%)'
  },
  dealsContainer: {
    display: "flex",
    alignItems: "flex-start",
    alignContent: "flex-start",
    gap: "8px",
    alignSelf: "stretch",
    flexWrap: "wrap",
    justifyContent: 'center'
  },
  customButton: {
    backgroundColor: '#FFF7E8 !important',
    padding: '13px 15px !important',
    color: '#734A00 !important',
    fontSize: '14px !important',
    marginRight: '10px !important',
    alignItems: 'center !important',
    fontFamily: 'Inter !important',
    fontStyle: 'normal !important',
    fontWeight: '400 !important',
    lineHeight: 'normal !important',
    letterSpacing: '-0.3px !important',
    borderRadius: '16px !important',
    border: 'None !important',
    textTransform: 'None !important'
  },
  growthGraph: {
    display: 'contents',
    // minWidth: '40%',
    minHeight: '60%',
    padding: '24px',
    flexDirection: 'column',
    alignItems: 'flex-start',
    gap: '8px',
    alignSelf: 'stretch',
    borderRadius: '16px',
    background: 'var(--White, #FFF)',
  },
  growthData: {
    display: 'flex',
    alignItems: 'flex-start',
    gap: '16px',
    flex: '1 0 0',
    alignSelf: 'stretch',
    minHeight: '25%'
  },
  growthTop: {
    display: 'flex',
    padding: '16px',
    flexDirection: 'column',
    alignItems: 'flex-start',
    gap: '16px',
    flex: '1 0 0',
    alignSelf: 'stretch',
    borderRadius: '16px',
    background: 'var(--White, #FFF)',
  },
  growthTitle: {
    color: 'var(--Mid-Gray, #7D7D7D) !important',
    fontFamily: 'Inter !important',
    fontSize: '16px !important',
    fontStyle: 'normal !important',
    fontWeight: '600 !important',
    lineHeight: 'normal !important',
    letterSpacing: '-0.4px !important',
  },
  growthMonth: {
    color: 'var(--Dark-Orange, #734A00) !important',
    fontFamily: 'Inter !important',
    fontSize: '24px !important',
    fontStyle: 'normal !important',
    fontWeight: '600 !important',
    lineHeight: 'normal !important',
    letterSpacing: '-0.2px !important',
  },
  growthName: {
    color: 'var(--Black, #131313) !important',
    fontFamily: 'Inter !important',
    fontSize: '12px !important',
    fontStyle: 'normal !important',
    fontWeight: '500 !important',
    lineHeight: 'normal !important',
    letterSpacing: '-0.3px !important',
  },
  growthContent: {
    color: '#454545 !important',
    fontFamily: 'Inter !important',
    fontSize: '10px !important',
    fontStyle: 'normal !important',
    fontWeight: '400 !important',
    lineHeight: 'normal !important',
    letterSpacing: '-0.3px !important',
  },
  growthYear: {
    color: 'var(--Orange, #FFA500) !important',
    fontFamily: 'Inter !important',
    fontSize: '16px !important',
    fontStyle: 'normal !important',
    fontWeight: '500 !important',
    lineHeight: 'normal !important',
    letterSpacing: '-0.2px !important',
  },
  profilePicture:{
    width:'24px !important',
    height:'24px !important',
    marginBottom: '4px'
  }
}));

export default useStyles;
